name: Build Eden Bot Docker Image and Update it to the CD Repo

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    name: 'Build the bot'
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        run: echo "UNIQ_ID=$(date +'%y%m%d')-${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: Ouput value
        run: echo ${{ env.BRANCH_NAME }}  ${{ env.UNIQ_ID }}

      - name: Repo Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: alex1237/eden-local

      - name: Build and push Docker image
        uses: docker/build-push-action@v3 # docker build & push
        with:
          context: .
          file: ./Dockerfile.local
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}